### ISSUE TITLE
[Feedback] DS1618+

### ISSUE THREAD

**Issue by Xeroxxx** [007revad/Synology_enable_Deduplication#25]
Synology DS1618+ with 7.2-64570 Update 3 

Regular SSD EMTEC X150 

Does not work. Deduplication menu does not show up. Scheduling is visible under global settings.

General Feedback:
--restore does not restore synoinfo.conf

**Comment by 007revad** [comment]
Do you have a Btrfs storage pool and a volume on the SSD?

Do you have [usage detail analysis](https://kb.synology.com/en-br/DSM/help/DSM/StorageManager/volume_view_usage?version=7) enabled for that Btrfs volume? 

Thanks for the feedback on restoring synoinfo.conf. I'll have a look at that.

**Comment by Xeroxxx** [comment]
> Do you have a Btrfs storage pool and a volume on the SSD?

Yes BTRFS, Yes on SDD

> Do you have [usage detail analysis](https://kb.synology.com/en-us/DSM/help/DSM/StorageManager/volume_view_usage?version=7) enabled for that Btrfs volume?

Yes

> Does the SSD drive or volume show any warnings in storage manager?

No

> Was it /etc/synoinfo.conf or /etc.defaults/synoinfo.conf that wasn't restored?

Only /etc/synoinfo.conf, yes NAS has been restarted twice after restore.
No there is no cronjob.

**Comment by karthik-panchap** [comment]
Experiencing the same issue as Xeroxxx (exactly as above on 7.2.1-69057 Update 3).

On SSDs, Dedup shows up under Global Setting/ Schedule
Both
  synogetkeyvalue /etc.defaults/synoinfo.conf support_btrfs_dedupe
  synogetkeyvalue /etc/synoinfo.conf support_btrfs_dedupe
show 'yes'.

Fix will be much appreciated as I'm running out of space.
Thanks in advance.

**Comment by 007revad** [comment]
Do you have 16GB or more memory?

**Comment by karthik-panchap** [comment]
> Do you have 16GB or more memory?

Yes.  64GB installed.

**Comment by 007revad** [comment]
I just tested with DSM 7.2.1 update 1 on my DS1821+ and it worked.

I can see your PCIe slot is empty.

Are these 2.5 inch SATA SSDs or NVMe drives?

If you run syno_enable_dedupe.sh with the --check option what does it return?

**Comment by 007revad** [comment]
Do both of the following commands return yes

`synogetkeyvalue /etc.defaults/synoinfo.conf support_btrfs_dedupe`
`synogetkeyvalue /etc/synoinfo.conf support_btrfs_dedupe`

I just tested with DSM 7.2.1 update 1 on my DS720+ and it also worked (even though it only has 2GB of memory!?!?)

I had previously run syno_enable_m2_volume on the DS720+ so /usr/lib/libhwcontrol.so.1 was already edited. What I did notice was:
- support_btrfs_dedupe did not exist in /etc.defaults/synoinfo.conf
- support_btrfs_dedupe existed in /etc/synoinfo.conf and was set to yes

After setting support_btrfs_dedupe to yes in /etc.defaults/synoinfo.conf and rebooting the deduplication option apperared in storage manager.

`sudo -i synosetkeyvalue /etc.defaults/synoinfo.conf support_btrfs_dedupe yes`

**Comment by karthik-panchap** [comment]
> `synogetkeyvalue /etc.defaults/synoinfo.conf support_btrfs_dedupe`

![ss](https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/e43a4577-6c20-439e-be57-c4b6e71cec9d)

> `synogetkeyvalue /etc/synoinfo.conf support_btrfs_dedupe`

![ss](https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/2ed3732f-1812-4354-9e6b-d60cd626696e)

> `sudo -i synosetkeyvalue /etc.defaults/synoinfo.conf support_btrfs_dedupe yes`

Ran the above and gave it a reboot - but still the same:

![ss](https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/8062266b-ccae-46a1-ab61-fd4af48e65c5)

**Comment by karthik-panchap** [comment]
Does it matter that I'm on DSM 7.2.1-69057 Update 3

**Comment by 007revad** [comment]
> Does it matter that the device is running DSM 7.2.1-69057 Update 3

Both my DS1821+ and DS720+ are running DSM 7.2.1-69057 Update 3 and the deduplication option is visible on them.

**Comment by 007revad** [comment]
> Does it matter that the device is running DSM 7.2.1-69057 Update 3

Both my DS1821+ and DS720+ are running DSM 7.2.1-69057 Update 3 and the deduplication option is visible on them. https://imgur.com/6JbKkab 

I just noticed I previously wrote 7.2.1 update 1 (which was wrong).

**Comment by karthik-panchap** [comment]
Good to know that DSM 7.2.1-69057 Update 3 is supported.
Thoughts on what to investigate next?
Any other logs I can provide you?
Jump on this google meet if you'd like to investigate.
https://meet.google.com/dzk-gjtx-ncd

**Comment by 007revad** [comment]
1. Do you see Data Deduplication Schedule in Storage Manager > Storage > Global Settings?
2. Do you have the Storage Analyzer package installed?
3. Do you have Volume Encryption enable on the SSD volume?
4. Do you have a shared folder with encryption enabled on that SSD volume?

Can you check if there's a /var/log/synoinfo.conf.bad file and when it was created:
`ls -l /var/log/synoinfo.conf.bad`

Can I get a copy of these 2 log files:
- /var/log/synobootup.log
- /var/log/synoplugin.log

**Comment by karthik-panchap** [comment]
> Do you see Data Deduplication Schedule in Storage Manager > Storage > Global Settings?

Yes.
![ss](https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/7a37c1c5-0eed-4259-b272-7ea4b10026a1)

> Do you have the Storage Analyzer package installed?

Yes.  Installed.  And Running.
![ss](https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/ed73eb9d-df49-4341-9175-d21df74a1fdb)

> Do you have Volume Encryption enabled on the SSD volume?

No.  

> Do you have a shared folder with encryption enabled on that SSD volume?

Hmm...  Nothing with encryption enabled.  But there are shared folders with immutable snapshots.  Could that be the issue?

> Can you check if there's a /var/log/synoinfo.conf.bad file and when it was created:
ls -l /var/log/synoinfo.conf.bad

No such file.
![ss](https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/6967f608-1fee-4990-a00d-4a1c5f4cb8ad)

> /var/log/synobootup.log
> /var/log/synoplugin.log

Is there a secure place to upload them?

**Comment by 007revad** [comment]
If you zip the logs you can attach the zip file to a comment. You can copy and paste, or drag and drop the zip file onto a comment, or use the "Paste, drop or click to add files" button/link below the comment when you're typing it.

**Comment by 007revad** [comment]
Hmm, no errors in those. Can you reply with the following logs:

/var/log/packages/StorageManager.log
/var/log/disk.log
/var/log/messages

**Comment by 007revad** [comment]
I just searched for files containing dedupe in DSM 7.2.1 for the DS1821+ and the DS1823xs+ and only 3 of those files are different between the 2 models.

1. dsm.full.0.list - which is just a list of files, permissions and hashes that DSM uses to check the files aren't corrupt.
2. btrfs.ko
3. synoinfo.conf

Both models use the same Storage Manager package.

I haven't looked in btrfs.ko yet but I don't expect there to differences relating to deduplication.

The interesting differences in synoinfo.conf are:

| DS1823xs+ | DS1821+ |
|--------------|------------|
| is_business_model="yes" | |
| support_auto_repair="yes" | support_auto_repair="no" |
| support_diffraid="yes" | |
| support_fc="yes" | |
| | support_syno_hybrid_raid="yes" |
| support_synodrive_ability="yes" | support_synodrive_ability="no" |
| support_synodrive_rule="2" | support_synodrive_rule="1" |
| support_uasp="yes" | support_uasp="no" |
| supportraidgroup="yes" | |

I can't find any info on what support_fc does. support_uasp only relates to USB drives. 

is_business_model, support_diffraid, support_synodrive_ability and support_synodrive_rule look interesting and need some investigation.

**Comment by karthik-panchap** [comment]
Interesting update.  Adding an NVME pool and volume provides the option to enable deduplication.

<img width="235" alt="ss" src="https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/8a325815-9cf4-46a4-8391-feba102547fc">

To rule out any issues with content on the SSD pool/volume - erased and rebuilt them.  While an option comes up to include the SSD pool/volume in *global* deduplication - the SSD volume still does not provide the option.

<img width="485" alt="ss" src="https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/b28102b6-f1b2-498c-8726-4fe247ee94eb">

<img width="676" alt="ss" src="https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/5f96566b-8446-497a-a263-5984d1195422">

**Comment by 007revad** [comment]
I wasn't seeing the deduplication option for my SATA SSD but I incorrectly assumed it was because it needed to at least be RAID 1 or 2 drive SHR. So I backed up then removed a SATA SSD from my PC and put it in my DS1821+ and created a 2 drive SATA SSD SHR volume with Btrfs and noticed a few things:

1. When you create a Btrfs SATA SSD or NVMe volume there's an option to enable Automatic Data Deduplication.
2. When you create a Btrfs NVMe volume you can later enable or disable Automatic Data Deduplication or manually run Deduplication.
3. When you create a Btrfs SATA SSD volume you **CANNOT** later enable or disable Automatic Data Deduplication or run Deduplication manually.

I though maybe it was because one of my SATA SSDs shows "Unknown" as the brand instead of Crucial. So I deleted the storage pool and created a new one on just 1 Intel SATA SSD but got the same result as point 3.

It looks like in DSM 7.2.1 (with Storage Manager now a package) you must enable Automatic Data Deduplication when creating the storage pool !?!? 

I don't know if this is a bug, or is normal behaviour, or is only happening because the drives aren't Synology drives.

At least now that I'm seeing the same behaviour as you I can test things here to try to find a solution.

**Comment by karthik-panchap** [comment]
> When you create a Btrfs SATA SSD or NVMe volume there's an option to enable Automatic Data Deduplication.
When you create a Btrfs NVMe volume you can later enable or disable Automatic Data Deduplication or manually run Deduplication.
When you create a Btrfs SATA SSD volume you CANNOT later enable or disable Automatic Data Deduplication or run Deduplication manually.

**Comment by 007revad** [comment]
This is proving to be harder than I hoped. The file I've been looking at is over 43,000 lines of javascript. Searching and reading a 43,000 line file is bad enough let alone javascript (which I have limited knowledge of).

While searching through that file I noticed some hard coded Synology drive model numbers and thought I'd come back to. Finding it again was time consuming because I was searching for SAT and HAT. When I did eventually find it it was for Synology NVMe drives that start with SVN (not SAT or HAT). I tried adding my SATA SSD's model number but that made no difference.

While viewing the volume **...** button of my SATA SSD volume in the storage manager page (using Chrome's Inspect option) I did manage to click on something that made a window popup asking if I was sure I wanted to run deduplication. So somehow I had clicked on the Manual Data Deduplication Run Now button (even though it wasn't visible).

**Comment by 007revad** [comment]
I think I'm close.

The file I'm looking at contains 371 instances of dedup so I decided to test if I was on the right track by trying to enable creating a storage pool on NVMe drives in a PCIe adaptor card, which only has 2 instance in the file... and it worked!

**Comment by 007revad** [comment]
@karthik-panchap 

I've got deduplication working on a SATA SSD by editing the file by hand. 

This change also enabled deduplication on HDDs. I'm not sure if that's a good thing or a bad thing. There was no option to enable Automatic Data Deduplication when creating the volume but the **...** menu allows me to enable or disable Automatic Data Deduplication or run Deduplication manually.

I just ran deduplication on a volume on a HDD and it worked.

I also noticed that all my drives (HDD, SATA SSD and NVME) have "Firmware Update" in their Action menu. This is obviously a side effect of making DSM think all the drives are Synology drives.

**Comment by 007revad** [comment]
@karthik-panchap 

I've released a new version that solves your issue of the missing Configure Data Duplication menu option.
https://github.com/007revad/Synology_enable_Deduplication/releases/tag/v1.1.12

Even though it is working perfectly I did notice something strange. After running the script with the --restore option (and checking that the 4 files were actually restored to default) the Configure Data Duplication menu option still appeared for SATA SSDs and HDDs.

**Comment by karthik-panchap** [comment]
> This change also enabled deduplication on HDDs. I'm not sure if that's a good thing or a bad thing.

This is a _great_ thing assuming it works with the SSD cache.  REFS (Windows Server) has this feature.

> I've released a new version that solves your issue of the missing Configure Data Duplication menu option

Good news:  Installing the latest version enabled the option and performing a manual dedupe run seemed to work.

[Potentially unrelated] Bad news:  After the test (manual dedupe run on a close to empty volume ~100mb), calling the syno_enable_dedupe.sh script with the --restore option prompted for a reboot that did not complete.  After waiting for ~2 hours and performing a forced reboot via ssh the DSM web GUI does not work.

<img width="739" alt="Screenshot 2023-12-22 at 9 26 03 PM jpeg" src="https://github.com/007revad/Synology_enable_Deduplication/assets/8904353/904abac3-c4bd-4870-8683-036ccf47f66d">

At this point, there seem few options but to reset the system.  Fortunately, I have backed everything up.  Again, the issue might have to do with my moving some of the shared folders off the SSD drive before enabling dedupe.  I'll test some more and get back.

Thanks for the progress and Happy Holidays!

**Comment by 007revad** [comment]
I've had that happen a few times. DSM really doesn't like some files being replaced while it's in use. Editing the files is okay.

I had a similar issue when I ran this script with the --restore option where it never rebooted and I couldn't access the UI (though SSH still worked). I only waited about 20 minutes before I pressed and held the power button on the NAS, expecting the NAS to shut down. The NAS beeped when I released the button... and then it shut down and booted up again. So it appeared it was stuck trying to shutdown until I forced it to shutdown.

After it came back online everything was normal... except deduplication was still enabled for HDDs and SATA SSDs. Even though running the script with the --check option shows it should not be enabled for HDDs and SATA SSDs.

I might change the restore process to edit the file instead of replacing the file with of copy form the backup.

**Comment by 007revad** [comment]
@karthik-panchap 

I've nearly finishing changing the restore option. Instead of copying backups over the top of files that DSM is using it will edit the values in those files to restore the values from the backup files. 

I've also discovered that one of the 3 files doesn't need to be edited in DSM 7.2.1. This file is the one that requires rebooting and causes issues in DSM if the file is replaced instead of being edited.

**Comment by 007revad** [comment]
@karthik-panchap 

I've released a new version with a much better restore process, and some other improvements.

https://github.com/007revad/Synology_enable_Deduplication/releases/tag/v1.2.14
